db:
  image: postgres:latest
  ports: ['5432']
  environment:
    - POSTGRES_PASSWORD
  volumes_from: [file]
file:
  command: echo "datastore"
  image: busybox
  command: /bin/sh
  volumes: [/var/lib/postgresql/data/]